import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = ROOT_DIR + "/db" + "/cs213.db"
UBC_CS213_URL = "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=CPSC&course=213"
LAB = "Laboratory"
VANCOUVER_TZ = "Canada/Pacific"
WINTER_TERM_1_RANGE_MONTH_DAYS = ["09/01", "12/31"]
WINTER_TERM_2_RANGE_MONTH_DAYS = ["01/01", "04/30"]
SUMMER_TERM_1_RANGE_MONTH_DAYS = ["05/01", "06/30"]
SUMMER_TERM_2_RANGE_MONTH_DAYS = ["07/01", "08/30"]
SUMMER_TERM_RANGE_MONTH_DAYS = [SUMMER_TERM_1_RANGE_MONTH_DAYS, SUMMER_TERM_2_RANGE_MONTH_DAYS]
WINTER_TERM_RANGE_MONTH_DAYS = [WINTER_TERM_1_RANGE_MONTH_DAYS, WINTER_TERM_2_RANGE_MONTH_DAYS]
SUMMER_TERM_IDX = 1
WINTER_TERM_IDX = 0
TERM_RANGE_MONTH_DAYS = [WINTER_TERM_IDX, SUMMER_TERM_IDX]
TERM_RANGE_MONTH_DAYS[WINTER_TERM_IDX] = WINTER_TERM_RANGE_MONTH_DAYS
TERM_RANGE_MONTH_DAYS[SUMMER_TERM_IDX] = SUMMER_TERM_RANGE_MONTH_DAYS
SUMMER_TERM_ABRV = 'S'
WINTER_TERM_ABRV = 'W'